#!/usr/bin/env python3
"""build_index.py — cross-bundle artifacts (HANDOFF §7).

Rebuilds the disposable search index (/state/wiki.db, SQLite FTS5) and, per
bundle, regenerates two markdown artifacts inside the runtime checkout (never
committed; the checkout is hard-reset every cycle before this runs):

  - cited-by-other-domains.md: inbound links from other bundles.
  - the `## Single Point of Failure` section of index.md: concepts whose
    `knows:` has exactly one entry.

Runs BEFORE build_site.sh in the loop so both render in the same cycle.
viz.html is emitted by the loop after the site build (it lands in /site).
"""
from __future__ import annotations

import argparse
import datetime
import re
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import yaml  # noqa: E402

import okf_validate as okf  # noqa: E402
from lint import load_meta  # noqa: E402  (same frontmatter parse as the linter)

SPOF_HEADING = "## Single Point of Failure"


def md_files(bundle: Path):
    for p in sorted(bundle.rglob("*.md")):
        if p.is_file() and ".git" not in p.parts:
            yield p


def build_db(root: Path, ids: list[str], db_path: Path) -> int:
    db_path.parent.mkdir(parents=True, exist_ok=True)
    tmp = db_path.with_suffix(".new")
    tmp.unlink(missing_ok=True)
    db = sqlite3.connect(tmp)
    db.execute("CREATE VIRTUAL TABLE pages USING "
               "fts5(bundle, path, title, type, classification, body)")
    n = 0
    for bid in ids:
        for p in md_files(root / bid):
            meta, body = load_meta(p)
            db.execute("INSERT INTO pages VALUES (?,?,?,?,?,?)",
                       (bid, p.relative_to(root / bid).as_posix(),
                        str(meta.get("title", p.stem)), str(meta.get("type", "")),
                        str(meta.get("classification", "")), body))
            n += 1
    db.commit()
    db.close()
    tmp.replace(db_path)  # atomic; readers keep the old db until the swap
    return n


def inbound_links(root: Path, ids: list[str], site_host: str) -> dict[str, dict]:
    """target-bundle -> {target-path -> [(source-bundle, source-path), ...]}"""
    link = re.compile(rf"https?://{re.escape(site_host)}/([a-z0-9-]+)/([^)#\s]+\.md)")
    out: dict[str, dict] = {bid: {} for bid in ids}
    for src in ids:
        for p in md_files(root / src):
            rel = p.relative_to(root / src).as_posix()
            for target in okf.collect_link_targets(p):
                m = link.match(target)
                if m and m.group(1) in ids and m.group(1) != src:
                    out[m.group(1)].setdefault(m.group(2), []).append((src, rel))
    return out


def write_cited_by(bundle: Path, bid: str, cites: dict, site_host: str) -> None:
    today = datetime.date.today().isoformat()
    lines = ["---", "type: Report",
             'title: "Cited by other domains"',
             'description: "Inbound cross-bundle links. Generated by the builder; do not edit."',
             "classification: P1", "tags: [generated]",
             "generated:", "  by: wiki-kit/builder", f'  at: "{today}"', "---", "",
             "# Cited by other domains", ""]
    if not cites:
        lines.append("*(no inbound links from other bundles)*")
    for path in sorted(cites):
        lines.append(f"* `/{path}` cited by:")
        for src_bid, src_rel in sorted(set(cites[path])):
            lines.append(f"  * [{src_bid}/{src_rel}](https://{site_host}/{src_bid}/{src_rel})")
    (bundle / "cited-by-other-domains.md").write_text("\n".join(lines) + "\n",
                                                      encoding="utf-8")


def spof_concepts(bundle: Path) -> list[tuple[str, str]]:
    hits = []
    for p in md_files(bundle):
        meta, _ = load_meta(p)
        knows = meta.get("knows")
        if isinstance(knows, list) and len(knows) == 1:
            hits.append((p.relative_to(bundle).as_posix(), str(knows[0])))
    return hits


def write_spof(bundle: Path) -> None:
    index = bundle / "index.md"
    if not index.is_file():
        return
    text = index.read_text(encoding="utf-8")
    rows = spof_concepts(bundle)
    body = ["", "Generated by the builder; do not edit by hand.", ""]
    body += [f"* [/{rel}](/{rel}) — only `{who}` knows it" for rel, who in rows] \
        or ["*(none: every page's `knows:` has two or more entries)*"]
    section = SPOF_HEADING + "\n" + "\n".join(body) + "\n"
    if SPOF_HEADING in text:
        # replace from the heading to the next H2 (or EOF)
        pattern = re.compile(re.escape(SPOF_HEADING) + r".*?(?=\n## |\Z)", re.S)
        text = pattern.sub(section, text, count=1)
    else:
        text = text.rstrip("\n") + "\n\n" + section
    index.write_text(text, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Rebuild wiki.db and cross-bundle pages.")
    ap.add_argument("--bundles", type=Path, required=True)
    ap.add_argument("--root", type=Path, default=Path("/bundles"))
    ap.add_argument("--db", type=Path, default=Path("/state/wiki.db"))
    args = ap.parse_args()

    cfg = yaml.safe_load(args.bundles.read_text())
    site_host = cfg["site_host"]
    ids = [b["id"] for b in cfg["bundles"] if (args.root / b["id"]).is_dir()]

    n = build_db(args.root, ids, args.db)
    inbound = inbound_links(args.root, ids, site_host)
    for bid in ids:
        write_cited_by(args.root / bid, bid, inbound[bid], site_host)
        write_spof(args.root / bid)
    print(f"indexed {n} pages across {len(ids)} bundle(s) into {args.db}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
