#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: wiki-kit node deployment (HANDOFF §11 step 9 green criteria).
# Run this ON THE NODE, inside your deploy directory (a clone of wiki-kit).
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

banner "wiki-kit deployment"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Node prerequisites"
say "This wizard deploys wiki-kit behind a Cloudflare Tunnel with Access."
say "Run it on the node, in the directory holding docker-compose.yml."
step "Install Docker Engine + compose plugin if missing:"
note "    curl -fsSL https://get.docker.com | sh"
step "Verify:"
note "    docker compose version"
pause "Docker ready? Press Enter."
if [[ ! -f docker-compose.yml ]]; then
  warn "docker-compose.yml not found in $(pwd) — cd to your wiki-kit clone and re-run."
  exit 1
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "bundles.yml"
say "bundles.yml lives only on this node. It names your site host and bundles."
if [[ ! -f bundles.yml ]]; then
  cp bundles.example.yml bundles.yml
  say "Created bundles.yml from bundles.example.yml."
fi
ask SITE_HOST "Wiki hostname (e.g. wiki.maybeit.work):"
write_env SITE_HOST "$SITE_HOST"
step "Edit bundles.yml now (another terminal): set site_host: $SITE_HOST,"
step "your brain-* repo URLs, and per-bundle readers: allowlists for MCP."
pause "bundles.yml edited? Press Enter."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Read-only GitHub PAT (bundle pulls)"
say "The builder clones brain-* repos with a fine-grained, read-only PAT."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: wiki-kit-pull · Expiration: your call."
step "Repository access: Only select repositories → every brain-* repo."
step "Permissions → Repository → Contents: Read-only. Nothing else."
step "Generate, then copy the token (github_pat_…)."
ask_secret GIT_TOKEN "Paste the PAT:"
write_env GIT_TOKEN "$GIT_TOKEN"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare Tunnel"
say "cloudflared is the only way in; port 8080 stays LAN/local."
open_url "https://one.dash.cloudflare.com/"
step "Networks → Tunnels → Create a tunnel → Cloudflared → name: wiki-kit."
step "On the connector page, copy the token from the install command"
step "(the long string after 'cloudflared service install')."
ask_secret TUNNEL_TOKEN "Paste the tunnel token:"
write_env TUNNEL_TOKEN "$TUNNEL_TOKEN"
step "Still in the tunnel: Public hostnames → Add:"
note "    hostname: $SITE_HOST   service: HTTP://web:8090"
pause "Public hostname added? Press Enter."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare Access application"
say "Access gates every request; Caddy trusts its authenticated-email header."
open_url "https://one.dash.cloudflare.com/"
step "Access → Applications → Add an application → Self-hosted."
step "Name: wiki · Domain: $SITE_HOST (path empty = whole site)."
step "Add a policy 'humans': Action Allow · Include → Emails (or your IdP"
step "group) → the people who may read the wiki."
pause "Application + Allow policy saved? Press Enter."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Access service token (Claude Code → /mcp)"
say "Non-browser clients authenticate with a service token, not a login."
open_url "https://one.dash.cloudflare.com/"
step "Access → Service credentials → Service Tokens → Create Service Token."
step "Name: claude-code · copy Client ID and Client Secret (shown once)."
ask CF_ACCESS_CLIENT_ID "Paste the Client ID:"
ask_secret CF_ACCESS_CLIENT_SECRET "Paste the Client Secret:"
step "Back in the wiki application's policies, add a second policy:"
note "    name: agents · Action: Service Auth · Include → Service Token → claude-code"
pause "Service Auth policy saved? Press Enter."
note "Heads-up: service-token calls carry no user email, so MCP shows them"
note "only bundles WITHOUT a readers: allowlist (HANDOFF §9)."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Start the stack"
say "Bringing up builder, web, mcp, and cloudflared."
docker compose --profile tunnel up -d --build
say "Waiting for the first build loop to publish status…"
for _ in $(seq 1 30); do
  if curl -fsS "http://localhost:8080/status" >/dev/null 2>&1; then break; fi
  sleep 5
done
if curl -fsS "http://localhost:8080/status" 2>/dev/null | head -c 300; then
  printf '\n'; say "Builder is reporting status."
else
  warn "No /status yet — check: docker compose logs builder"
fi
pause "Press Enter to continue to verification."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Verify: phone + Claude Code"
step "On your phone (off wifi, on mobile data), open:"
note "    https://$SITE_HOST/<bundle-id>/"
say "You should hit the Access login, then the wiki. That's criterion one."
pause "Phone works? Press Enter."
step "On your laptop, register the MCP server with Claude Code:"
note "    claude mcp add wiki --transport http https://$SITE_HOST/mcp \\"
note "      --header \"CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID\" \\"
note "      --header \"CF-Access-Client-Secret: <the secret>\""
step "Then in a Claude Code session ask it to call the wiki search tool."
say "A search result back through the tunnel is criterion two — step 9 green."
pause "Claude Code search works? Press Enter."

finish
note "Step 10 closes the loop: tag v0.1.0 in wiki-kit, then set image pins"
note "to ghcr.io/nineW0nW0n/wiki-kit:0.1.0."
